-- Sprint 17 (suite 2, intégration) — Règles allow_program réelles, validées
-- par Dr Nikiema le 23/08/2026 (QUESTIONS_ALLOW_PROGRAM_20260823.docx,
-- réponses aux Questions 1 et 2), traduisant sa réponse B4 (20/08/2026).
--
-- Logique retenue, littéralement conforme à ses réponses :
--   - le fait `niveau` (débutant/intermédiaire/avancé) est calculé côté
--     application (classifyInitialProfileLevel, packages/domain/src/programs.ts)
--     à partir de physical_activity_level et du statut de dépistage — PAS
--     par ces règles elles-mêmes, qui restent de simples correspondances
--     pathologie + niveau + statut -> programme.
--   - dépistage vert : niveau tel que calculé (1-2 -> débutant, 3 ->
--     intermédiaire, 4-5 -> avancé) -> le programme du même niveau.
--   - dépistage orange : niveau initial déjà plafonné à débutant par
--     classifyInitialProfileLevel — mais la condition ci-dessous restreint
--     EXPLICITEMENT et INDÉPENDAMMENT les règles intermédiaire/avancé au seul
--     statut vert (défense en profondeur : même en cas de bug côté calcul du
--     fait niveau, un dépistage orange ne peut jamais déclencher autre chose
--     que le programme débutant, conformément à sa réponse Q2).
--   - dépistage rouge / pending_validation : niveau = null (jamais transmis)
--     -> aucune règle ne matche jamais -> MEDICAL_PARAMETER_REQUIRED, comme
--     avant ce fichier.

insert into public.clinical_rules
  (rule_id, pathology, condition, severity, action, message, program_id, active, version, validated_by, validated_date)
values
  ('ALLOW_PROGRAM_LOMBALGIE_COMMUNE_DEBUTANT', 'LOMBALGIE_COMMUNE', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme LOMBALGIE_COMMUNE_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'LOMBALGIE_COMMUNE_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_LOMBALGIE_COMMUNE_INTERMEDIAIRE', 'LOMBALGIE_COMMUNE', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme LOMBALGIE_COMMUNE_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'LOMBALGIE_COMMUNE_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_LOMBALGIE_COMMUNE_AVANCE', 'LOMBALGIE_COMMUNE', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme LOMBALGIE_COMMUNE_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'LOMBALGIE_COMMUNE_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_GENOU_DEBUTANT', 'ARTHROSE_GENOU', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_GENOU_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_GENOU_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_GENOU_INTERMEDIAIRE', 'ARTHROSE_GENOU', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_GENOU_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_GENOU_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_GENOU_AVANCE', 'ARTHROSE_GENOU', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_GENOU_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_GENOU_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_HANCHE_DEBUTANT', 'ARTHROSE_HANCHE', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_HANCHE_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_HANCHE_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_HANCHE_INTERMEDIAIRE', 'ARTHROSE_HANCHE', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_HANCHE_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_HANCHE_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_ARTHROSE_HANCHE_AVANCE', 'ARTHROSE_HANCHE', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme ARTHROSE_HANCHE_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'ARTHROSE_HANCHE_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_POLYARTHRITE_RHUMATOIDE_DEBUTANT', 'POLYARTHRITE_RHUMATOIDE', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme POLYARTHRITE_RHUMATOIDE_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'POLYARTHRITE_RHUMATOIDE_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_POLYARTHRITE_RHUMATOIDE_INTERMEDIAIRE', 'POLYARTHRITE_RHUMATOIDE', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme POLYARTHRITE_RHUMATOIDE_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'POLYARTHRITE_RHUMATOIDE_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_POLYARTHRITE_RHUMATOIDE_AVANCE', 'POLYARTHRITE_RHUMATOIDE', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme POLYARTHRITE_RHUMATOIDE_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'POLYARTHRITE_RHUMATOIDE_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_SPONDYLOARTHRITE_AXIALE_DEBUTANT', 'SPONDYLOARTHRITE_AXIALE', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme SPONDYLOARTHRITE_AXIALE_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'SPONDYLOARTHRITE_AXIALE_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_SPONDYLOARTHRITE_AXIALE_INTERMEDIAIRE', 'SPONDYLOARTHRITE_AXIALE', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme SPONDYLOARTHRITE_AXIALE_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'SPONDYLOARTHRITE_AXIALE_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_SPONDYLOARTHRITE_AXIALE_AVANCE', 'SPONDYLOARTHRITE_AXIALE', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme SPONDYLOARTHRITE_AXIALE_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'SPONDYLOARTHRITE_AXIALE_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_OSTEOPOROSE_DEBUTANT', 'OSTEOPOROSE', '{"all":[{"field":"niveau","operator":"equals","value":"debutant"},{"field":"screening","operator":"in","value":["vert","orange"]}]}', 'info', 'allow_program', 'Programme OSTEOPOROSE_DEBUTANT_01 attribué automatiquement (niveau initial debutant, dépistage vert ou orange (plafonné à débutant en orange, réponse Q2 du 23/08/2026)) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'OSTEOPOROSE_DEBUTANT_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_OSTEOPOROSE_INTERMEDIAIRE', 'OSTEOPOROSE', '{"all":[{"field":"niveau","operator":"equals","value":"intermediaire"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme OSTEOPOROSE_INTERMEDIAIRE_01 attribué automatiquement (niveau initial intermediaire, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'OSTEOPOROSE_INTERMEDIAIRE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23'),
  ('ALLOW_PROGRAM_OSTEOPOROSE_AVANCE', 'OSTEOPOROSE', '{"all":[{"field":"niveau","operator":"equals","value":"avance"},{"field":"screening","operator":"in","value":["vert"]}]}', 'info', 'allow_program', 'Programme OSTEOPOROSE_AVANCE_01 attribué automatiquement (niveau initial avance, dépistage vert) — règle dérivée de B4 et des réponses du 23/08/2026, aucun contenu médical nouveau.', (select program_id from public.programs where program_code = 'OSTEOPOROSE_AVANCE_01'), true, 'V1.0', 'Dr Wendtongo Brice Florent NIKIEMA', '2026-08-23')
on conflict (rule_id) do update set
  condition = excluded.condition,
  program_id = excluded.program_id,
  message = excluded.message,
  active = excluded.active,
  updated_at = now();
